const SOCKET_ENDPOINT = "http://192.168.1.243:3000";
const EVENTS = {
  ON_CONNECTION: "connection",
  ON_DISCONNECT: "disconnect",
  ON_RATE: "RATE",
  ON_POSLIST: "POSLIST",
  ON_ORDERLIST: "ORDERLIST",
  ON_ACCOUNT: "ACCOUNT",
  ON_PRICE_TICK: "FAT_PRICE_TICK",
  ON_ORDER_RESPONSE: "ORDER_RESPONSE",
  ON_ORDER_REQUEST: "ORDER_REQUEST",
  ON_LOG: "FAT_LOG",
  ON_STATUS: "ACCOUNT_STATUS",
};

export { SOCKET_ENDPOINT, EVENTS };
