const SOCKET_ENDPOINT = "http://167.179.68.107:4001";
const EVENTS = {
    ON_CONNECTION: 'connection',
    ON_DISCONNECT: 'disconnect',
    ON_RATE: 'RATE',
    ON_POSLIST: 'POSLIST',
    ON_ORDERLIST: 'ORDERLIST',
    ON_ACCOUNT: 'ACCOUNT',
    ON_PRICE_TICK: 'FAT_PRICE_TICK',
    ON_ORDER_RESPONSE: 'ORDER_RESPONSE',
    ON_ORDER_REQUEST: 'ORDER_REQUEST',
    ON_LOG: 'FAT_LOG', 
}

export { SOCKET_ENDPOINT, EVENTS };
