const SOCKET_ENDPOINT = "http://localhost:4001";
const EVENTS = {
    ON_CONNECTION: 'connection',
    ON_DISCONNECT: 'disconnect',
    ON_SET_PARAM: 'FAT_PARAM_V2C',
    ON_GET_PARAM: 'FAT_PARAM_C2V',
    ON_VARIABEL: 'FAT_VARIABLE',
    ON_POSITIONS: 'FAT_POSITIONS',
    ON_POSHISTORY: 'FAT_POSHISTORY',
    ON_LOG: 'FAT_LOG',
    ON_ACCOUNT: 'FAT_ACCOUNT',
    ON_PRICE_TICK: 'FAT_PRICE_TICK',
}

export { SOCKET_ENDPOINT, EVENTS };
